# Generated by Django 3.2.13 on 2022-05-30 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryExpenses',
        ),
        migrations.AddField(
            model_name='dailyexpenses',
            name='expense',
            field=models.CharField(choices=[('STATIONARY', 'STATIONARY'), ('EATERIES', 'EATERIES'), ('COMPUTER ACCESSORIES', 'COMPUTER ACCESSORIES')], default='EATERIES', max_length=21),
        ),
        migrations.AlterField(
            model_name='dailyexpenses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyexpenses',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
