# Generated by Django 3.2.13 on 2022-05-30 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20220530_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('persons', models.CharField(choices=[('SUNDARI', 'SUNDARI'), ('MUNIYANDI', 'MUNIYANDI'), ('GOPAL', 'GOPAL'), ('KUMAR', 'KUMAR'), ('RANJANI', 'RANJANGI'), ('OTHERS', 'OTHERS')], default='GOPAL', max_length=10)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
