# Generated by Django 3.2.13 on 2022-05-30 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_salaryexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryexpenses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
