# Generated by Django 3.2.13 on 2022-05-29 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('shop_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='big.location')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('no_of_cylinders', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('no_of_empty', models.PositiveSmallIntegerField(default=0)),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='big.shopdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rate', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=8)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='big.shopdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('collection_amount', models.PositiveIntegerField()),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='big.shopdetails')),
            ],
        ),
    ]
