# Generated by Django 3.2.13 on 2022-05-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('big', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big.shopdetails'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big.shopdetails'),
        ),
    ]
